# File: docker-compose.yml

version: "3.9"

services:
  # Service worker AWS Rainfall
  aws_rainfall_worker:
    # Menggunakan Dockerfile di direktori saat ini
    build: .

    # Nama container
    container_name: worker_current_rainfall

    # Memuat semua variabel ENV dari file .env di direktori root
    env_file:
      - .env

    # Volume: Penting untuk menyimpan file failover_logs di host
    # Ini memastikan log kegagalan tetap ada meskipun container di-restart/dibuang.
    volumes:
      - ./failover_logs:/app/failover_logs

    # Perintah utama untuk menjalankan worker.py
    # Ini akan menjalankan fungsi run_worker_app() yang berisi loop tak terbatas
    command: ["python", "worker_rainfall.py"] 

    # Kebijakan restart KRITIS: 
    # Secara otomatis me-restart jika container keluar dengan kode non-nol (sys.exit(1))
    restart: always

    # Opsional: Jika Anda juga menjalankan DB, tambahkan ketergantungan
    # depends_on:
    #   - your_database_service
